version: "3.9"
services:
  bot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DOKKU_HOST: "dokku"
      DOKKU_USER: "dokku"
      DOKKU_SSH_PORT: 22
      DOKKU_HTTP_PORT: 80
      DOKKU_HTTPS_PORT: 443
      POSTGRES_PASSWORD: postgres-testing
      SLACK_REDIRECT_URI: http://localhost:5000/oauth/code
      SLACK_CLIENT_ID: "2210535565.1990079909558"
      SLACK_CLIENT_SECRET: 1f2201a7312f9a00515b3f18b7009546
      HAAS_DEV: "true"
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ".:/code"
      - "./dokku_data:/dokku"
      - "./dokkud_sock:/var/run/dokku-daemon"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash ./run_dev.sh
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres-testing
      POSTGRES_DB: haas
    volumes:
      - "db_volume:/var/lib/postgresql/data"
  dokku:
    build:
      context: .
      dockerfile: dokku.dev.Dockerfile
    depends_on:
      - bot
    ports:
      - "3022:22"
      - "3080:80"
      - "3443:443"
    volumes:
      - "./dokku_data:/mnt/dokku"
      - "./dokkud_sock:/var/run/dokku-daemon"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  db_volume:
