#!/bin/bash

# Clean up from previous builds
rm -rf subcommands/
rm commands
rm triggers

cd $(dirname "$0")/dokku_plugin

# Build commands
go build -o ../commands command/command.go

# Build subcommands
mkdir -p ../subcommands/

for i in subcommands/**/*.go; do
    output=$(basename $i | cut -f 1 -d '.')

    go build -o ../subcommands/$output $i
done

# Build triggers
go build -o ../triggers triggers/triggers.go

cd ..

for t in post-deploy; do
    ln -sf triggers $t
done

echo "Installed!"
