#!/bin/bash

# Clean up
rm -rf subcommands/
rm commands

# Build commands
go build -o commands src/command/command.go

# Build subcommands
mkdir subcommands/

for i in src/subcommands/**/*.go; do
    output=$(basename $i | cut -f 1 -d '.')

    go build -o subcommands/$output $i
done

# Remove source if running in prod
if [ "$1" != "dev" ]
then
    echo "Running prod build"

    rm -rf src/
fi

echo "Installed!"