name: Deploy

on:
  push:
    branches: [master]

jobs:
  config:
    name: Deploy Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        name: Add SSH key
      - run: ./.github/deploy_config.sh
        name: Deploy config
  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [config]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dokku/github-action@v1.0.2
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@45.55.45.5/haas"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [config]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dokku/github-action@v1.0.2
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@45.55.45.5/haas-frontend"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  proxy:
    name: Deploy Proxy
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dokku/github-action@v1.0.2
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@45.55.45.5/haas-proxy"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
