name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn install
        working-directory: ./frontend

      - run: yarn build
        working-directory: ./frontend

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn install
        working-directory: ./frontend

      - run: echo "yarn format:check"
        working-directory: ./frontend
